import nx from '@nx/eslint-plugin';

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    // types/generated/** is Strapi's own typegen output (regenerated by
    // `strapi develop`/`ts:generate-types`, not hand-authored) -- same
    // "don't lint generated code" reasoning as dist/out-tsc, just not
    // caught until a real lint CI run first exercised this repo (see
    // CLAUDE.md's "Source control & CI/CD" section / ../TODO.md's
    // "Scaling to multi-team ownership").
    ignores: ['**/dist', '**/out-tsc', '**/types/generated/**'],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$'],
          depConstraints: [
            // Tightened ahead of the per-app repo split (see CLAUDE.md's
            // "Monorepo -> future split" section): each app repo will only
            // have its own scope's libs plus the published shared-*
            // packages available, so an in-repo import that would become
            // impossible to resolve after the split needs to fail lint
            // *now*, while it's a one-PR fix instead of a cross-repo
            // rewrite. This replaced a wide-open `sourceTag: '*'` ->
            // `onlyDependOnLibsWithTags: ['*']` constraint that didn't
            // actually restrict anything -- it's why a real violation
            // (apps/shell importing an employment-life-events-scoped lib)
            // went uncaught until the split forced the issue.
            { sourceTag: 'type:e2e', onlyDependOnLibsWithTags: ['*'] },
            { sourceTag: 'scope:shared', onlyDependOnLibsWithTags: ['scope:shared'] },
          ],
        },
      ],
    },
  },
  {
    files: [
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
    ],
    // Override or add rules here
    rules: {},
  },
  {
    // Strapi's `src/index.ts` must export a `register` lifecycle hook even
    // when there's genuinely nothing to do at registration time (all real
    // seeding happens in `bootstrap`, see that file) -- Strapi's own
    // contract, not something this codebase can satisfy differently. A
    // deliberate rule override, not an inline disable comment, per
    // CLAUDE.md's "Linting" section.
    files: ['tools/cms/strapi/src/index.ts'],
    rules: {
      '@typescript-eslint/no-empty-function': 'off',
    },
  },
];
