apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.redis.name }}
    app.kubernetes.io/component: session-cache
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.redis.name }}
    app.kubernetes.io/component: session-cache
  ports:
    - port: {{ .Values.redis.servicePort | default .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}
