apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
    app.kubernetes.io/component: unleash-postgres
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
    app.kubernetes.io/component: unleash-postgres
  ports:
    - port: {{ .Values.postgres.servicePort | default .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}
