apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.unleash.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.unleash.name }}
    app.kubernetes.io/component: unleash
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.unleash.name }}
    app.kubernetes.io/component: unleash
  ports:
    - port: {{ .Values.unleash.servicePort | default .Values.unleash.containerPort }}
      targetPort: {{ .Values.unleash.containerPort }}
