apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.strapi.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.strapi.name }}
    app.kubernetes.io/component: cms
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.strapi.name }}
    app.kubernetes.io/component: cms
  ports:
    - port: {{ .Values.strapi.servicePort | default .Values.strapi.containerPort }}
      targetPort: {{ .Values.strapi.containerPort }}
