apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelCollector.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.otelCollector.name }}
    app.kubernetes.io/component: observability
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.otelCollector.name }}
    app.kubernetes.io/component: observability
  ports:
    - name: otlp-http
      port: {{ .Values.otelCollector.otlpHttpPort }}
      targetPort: {{ .Values.otelCollector.otlpHttpPort }}
    - name: prometheus
      port: {{ .Values.otelCollector.prometheusPort }}
      targetPort: {{ .Values.otelCollector.prometheusPort }}
