/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ScdsCardTone } from "./components/scds-card/scds-card";
import { ScdsListColumn } from "./components/scds-multi-column-list/scds-multi-column-list";
export { ScdsCardTone } from "./components/scds-card/scds-card";
export { ScdsListColumn } from "./components/scds-multi-column-list/scds-multi-column-list";
export namespace Components {
    /**
     * A card that extends `gcds-card` with what it doesn't have: a variant that
     * renders without a destination link (`gcds-card` renders nothing at all if
     * `href` is omitted -- both `cardTitle` and `href` are required props on the
     * underlying Stencil component), a severity tone badge reusing
     * `gcds-notice`'s tone vocabulary/icons, and a footer actions slot.
     * Framework-agnostic (Stencil, shadow DOM). Angular consumers get a typed
     * wrapper via
     * @tn4consulting /shared-ui-scds (auto-generated from this
     * package); other frameworks (e.g. React) use this custom element directly.
     */
    interface ScdsCard {
        "cardTitle": string;
        /**
          * @default 'h3'
         */
        "cardTitleTag": 'h3' | 'h4' | 'h5' | 'h6';
        "description"?: string;
        "href"?: string;
        "imgAlt"?: string;
        "imgSrc"?: string;
        "rel"?: string;
        "target"?: string;
        "tone"?: ScdsCardTone;
        "toneLabel"?: string;
    }
    /**
     * A multi-column list for data GCDS has no component for (e.g. tasks,
     * documents) that isn't a literal table (`gcds-table`). Real `<ul>`/`<li>`
     * markup with CSS Grid columns at wide viewports, collapsing to stacked
     * "label: value" rows at GCDS's own 48em breakpoint. Each cell's column
     * header is always present as real text (visually hidden at wide
     * viewports, shown inline once stacked) rather than relying on
     * CSS-generated content, since this is a list, not a `<table>`, so there's
     * no native mechanism associating a cell with its column header for
     * assistive tech otherwise.
     * `items`/`columns`/`trackBy` are DOM properties, not HTML attributes
     * (they're non-primitive) -- set them via the element's JS properties, not
     * as JSX/HTML attribute strings. Framework-agnostic (Stencil, shadow DOM).
     * The Angular-only `column.template` `TemplateRef` escape hatch that
     * existed on the hand-written predecessor of this component is
     * deliberately dropped here -- no web-component equivalent, and no real
     * consumer needs it (see mfe-pot-platform's TODO/plan history).
     */
    interface ScdsMultiColumnList {
        /**
          * @default []
         */
        "columns": ScdsListColumn[];
        /**
          * @default 'No items.'
         */
        "emptyLabel": string;
        /**
          * @default []
         */
        "items": unknown[];
        "listLabel"?: string;
        /**
          * @default (item) => item
         */
        "trackBy": (item: unknown) => unknown;
    }
}
export interface ScdsCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScdsCardElement;
}
declare global {
    interface HTMLScdsCardElementEventMap {
        "scdsClick": string;
    }
    /**
     * A card that extends `gcds-card` with what it doesn't have: a variant that
     * renders without a destination link (`gcds-card` renders nothing at all if
     * `href` is omitted -- both `cardTitle` and `href` are required props on the
     * underlying Stencil component), a severity tone badge reusing
     * `gcds-notice`'s tone vocabulary/icons, and a footer actions slot.
     * Framework-agnostic (Stencil, shadow DOM). Angular consumers get a typed
     * wrapper via
     * @tn4consulting /shared-ui-scds (auto-generated from this
     * package); other frameworks (e.g. React) use this custom element directly.
     */
    interface HTMLScdsCardElement extends Components.ScdsCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScdsCardElementEventMap>(type: K, listener: (this: HTMLScdsCardElement, ev: ScdsCardCustomEvent<HTMLScdsCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScdsCardElementEventMap>(type: K, listener: (this: HTMLScdsCardElement, ev: ScdsCardCustomEvent<HTMLScdsCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScdsCardElement: {
        prototype: HTMLScdsCardElement;
        new (): HTMLScdsCardElement;
    };
    /**
     * A multi-column list for data GCDS has no component for (e.g. tasks,
     * documents) that isn't a literal table (`gcds-table`). Real `<ul>`/`<li>`
     * markup with CSS Grid columns at wide viewports, collapsing to stacked
     * "label: value" rows at GCDS's own 48em breakpoint. Each cell's column
     * header is always present as real text (visually hidden at wide
     * viewports, shown inline once stacked) rather than relying on
     * CSS-generated content, since this is a list, not a `<table>`, so there's
     * no native mechanism associating a cell with its column header for
     * assistive tech otherwise.
     * `items`/`columns`/`trackBy` are DOM properties, not HTML attributes
     * (they're non-primitive) -- set them via the element's JS properties, not
     * as JSX/HTML attribute strings. Framework-agnostic (Stencil, shadow DOM).
     * The Angular-only `column.template` `TemplateRef` escape hatch that
     * existed on the hand-written predecessor of this component is
     * deliberately dropped here -- no web-component equivalent, and no real
     * consumer needs it (see mfe-pot-platform's TODO/plan history).
     */
    interface HTMLScdsMultiColumnListElement extends Components.ScdsMultiColumnList, HTMLStencilElement {
    }
    var HTMLScdsMultiColumnListElement: {
        prototype: HTMLScdsMultiColumnListElement;
        new (): HTMLScdsMultiColumnListElement;
    };
    interface HTMLElementTagNameMap {
        "scds-card": HTMLScdsCardElement;
        "scds-multi-column-list": HTMLScdsMultiColumnListElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * A card that extends `gcds-card` with what it doesn't have: a variant that
     * renders without a destination link (`gcds-card` renders nothing at all if
     * `href` is omitted -- both `cardTitle` and `href` are required props on the
     * underlying Stencil component), a severity tone badge reusing
     * `gcds-notice`'s tone vocabulary/icons, and a footer actions slot.
     * Framework-agnostic (Stencil, shadow DOM). Angular consumers get a typed
     * wrapper via
     * @tn4consulting /shared-ui-scds (auto-generated from this
     * package); other frameworks (e.g. React) use this custom element directly.
     */
    interface ScdsCard {
        "cardTitle": string;
        /**
          * @default 'h3'
         */
        "cardTitleTag"?: 'h3' | 'h4' | 'h5' | 'h6';
        "description"?: string;
        "href"?: string;
        "imgAlt"?: string;
        "imgSrc"?: string;
        /**
          * Re-emits `gcds-card`'s own `gcdsClick` (fired only in link mode).
         */
        "onScdsClick"?: (event: ScdsCardCustomEvent<string>) => void;
        "rel"?: string;
        "target"?: string;
        "tone"?: ScdsCardTone;
        "toneLabel"?: string;
    }
    /**
     * A multi-column list for data GCDS has no component for (e.g. tasks,
     * documents) that isn't a literal table (`gcds-table`). Real `<ul>`/`<li>`
     * markup with CSS Grid columns at wide viewports, collapsing to stacked
     * "label: value" rows at GCDS's own 48em breakpoint. Each cell's column
     * header is always present as real text (visually hidden at wide
     * viewports, shown inline once stacked) rather than relying on
     * CSS-generated content, since this is a list, not a `<table>`, so there's
     * no native mechanism associating a cell with its column header for
     * assistive tech otherwise.
     * `items`/`columns`/`trackBy` are DOM properties, not HTML attributes
     * (they're non-primitive) -- set them via the element's JS properties, not
     * as JSX/HTML attribute strings. Framework-agnostic (Stencil, shadow DOM).
     * The Angular-only `column.template` `TemplateRef` escape hatch that
     * existed on the hand-written predecessor of this component is
     * deliberately dropped here -- no web-component equivalent, and no real
     * consumer needs it (see mfe-pot-platform's TODO/plan history).
     */
    interface ScdsMultiColumnList {
        /**
          * @default []
         */
        "columns"?: ScdsListColumn[];
        /**
          * @default 'No items.'
         */
        "emptyLabel"?: string;
        /**
          * @default []
         */
        "items"?: unknown[];
        "listLabel"?: string;
        /**
          * @default (item) => item
         */
        "trackBy"?: (item: unknown) => unknown;
    }

    interface ScdsCardAttributes {
        "cardTitle": string;
        "cardTitleTag": 'h3' | 'h4' | 'h5' | 'h6';
        "description": string;
        "href": string;
        "rel": string;
        "target": string;
        "imgSrc": string;
        "imgAlt": string;
        "tone": ScdsCardTone;
        "toneLabel": string;
    }
    interface ScdsMultiColumnListAttributes {
        "emptyLabel": string;
        "listLabel": string;
    }

    interface IntrinsicElements {
        "scds-card": Omit<ScdsCard, keyof ScdsCardAttributes> & { [K in keyof ScdsCard & keyof ScdsCardAttributes]?: ScdsCard[K] } & { [K in keyof ScdsCard & keyof ScdsCardAttributes as `attr:${K}`]?: ScdsCardAttributes[K] } & { [K in keyof ScdsCard & keyof ScdsCardAttributes as `prop:${K}`]?: ScdsCard[K] } & OneOf<"cardTitle", ScdsCard["cardTitle"], ScdsCardAttributes["cardTitle"]>;
        "scds-multi-column-list": Omit<ScdsMultiColumnList, keyof ScdsMultiColumnListAttributes> & { [K in keyof ScdsMultiColumnList & keyof ScdsMultiColumnListAttributes]?: ScdsMultiColumnList[K] } & { [K in keyof ScdsMultiColumnList & keyof ScdsMultiColumnListAttributes as `attr:${K}`]?: ScdsMultiColumnListAttributes[K] } & { [K in keyof ScdsMultiColumnList & keyof ScdsMultiColumnListAttributes as `prop:${K}`]?: ScdsMultiColumnList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A card that extends `gcds-card` with what it doesn't have: a variant that
             * renders without a destination link (`gcds-card` renders nothing at all if
             * `href` is omitted -- both `cardTitle` and `href` are required props on the
             * underlying Stencil component), a severity tone badge reusing
             * `gcds-notice`'s tone vocabulary/icons, and a footer actions slot.
             * Framework-agnostic (Stencil, shadow DOM). Angular consumers get a typed
             * wrapper via
             * @tn4consulting /shared-ui-scds (auto-generated from this
             * package); other frameworks (e.g. React) use this custom element directly.
             */
            "scds-card": LocalJSX.IntrinsicElements["scds-card"] & JSXBase.HTMLAttributes<HTMLScdsCardElement>;
            /**
             * A multi-column list for data GCDS has no component for (e.g. tasks,
             * documents) that isn't a literal table (`gcds-table`). Real `<ul>`/`<li>`
             * markup with CSS Grid columns at wide viewports, collapsing to stacked
             * "label: value" rows at GCDS's own 48em breakpoint. Each cell's column
             * header is always present as real text (visually hidden at wide
             * viewports, shown inline once stacked) rather than relying on
             * CSS-generated content, since this is a list, not a `<table>`, so there's
             * no native mechanism associating a cell with its column header for
             * assistive tech otherwise.
             * `items`/`columns`/`trackBy` are DOM properties, not HTML attributes
             * (they're non-primitive) -- set them via the element's JS properties, not
             * as JSX/HTML attribute strings. Framework-agnostic (Stencil, shadow DOM).
             * The Angular-only `column.template` `TemplateRef` escape hatch that
             * existed on the hand-written predecessor of this component is
             * deliberately dropped here -- no web-component equivalent, and no real
             * consumer needs it (see mfe-pot-platform's TODO/plan history).
             */
            "scds-multi-column-list": LocalJSX.IntrinsicElements["scds-multi-column-list"] & JSXBase.HTMLAttributes<HTMLScdsMultiColumnListElement>;
        }
    }
}
